# Generated by Django 4.1 on 2022-08-08 06:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=50)),
                ('poster_path', cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo')),
                ('overview', models.CharField(max_length=500)),
                ('release_date', models.DateTimeField()),
            ],
        ),
    ]
